version: '3.7'

services:
  chromium_builder:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      # beacuse symlinks path should be same
      - $WORKSPACE/chromium:$WORKSPACE/chromium
    environment:
      TARGET_CPU: $TARGET_CPU
    command: >
        bash -c "
        cd /chromium/src/ &&
        gn gen out/android_$$TARGET_CPU &&
        cd /chromium/src/ &&
        autoninja -C out/android_$$TARGET_CPU chrome_public_apk"
